//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMonitorWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataMonitorEntities : DbContext
    {
        public DataMonitorEntities()
            : base("name=DataMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Threashold> Threasholds { get; set; }
        public virtual DbSet<Watcher> Watchers { get; set; }
    }
}
